##### User Login
POST http://localhost:3201/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"himanshumahara.ps@gmail.com"
}


##### User Verfiy hash
POST http://localhost:3201/user/verify/hash HTTP/1.1
Content-Type: application/json

{
    "hash":"62d2eecee72f20802c073717"
}

##### User Verfiy OTP
POST http://localhost:3201/user/verify/otp HTTP/1.1
Content-Type: application/json

{
    "hash":"62d3cc3c3ec0e2d70445cd10",
    "otp":"886601"
}

##### User Verfiy OTP
POST http://localhost:3201/user/auth HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyZDJlZGNjOGU4OTRhZTUxNTVjZTJjNSIsImVtYWlsIjoiaGltYW5zaHVtYWhhcmEucHNAZ21haWwuY29tIiwiX192IjowLCJjcmVhdGVkQXQiOiIyMDIyLTA3LTE2VDE2OjU2OjQ0Ljg4MFoiLCJvdHAiOiIkMmIkMTAkeEVTeUMwSGJJd0pLcXhKaGhuLnFHTzZpMXYxRXA1TTdBYkY2S2NYdFdOU1ZFeUJrNi4zRG0iLCJ2ZXJpZnlLZXkiOiI2MmQzY2MzYzNlYzBlMmQ3MDQ0NWNkMTAifSwiaWF0IjoxNjU4MDU0MTU0fQ.jdXWzh4vT46FMcGatbCSGG77GlxJIpRySavvN8SPEbk




##### User Create Profile
POST http://localhost:3200/user/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer JWT_TOKEN

{
    "oracleID":"123322",
    "careerStage":"Senior Associate",
    "primaryCapability":"XT"
}